version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./app/backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./app/backend/.env
    depends_on:
      - mongo
    volumes:
      - ./app/backend:/app

volumes:
  mongo-data:
  
